<a href="https://colab.research.google.com/github/Liang130520/Tibame-TeamProject/blob/main/TeamProject_api_4%E7%89%88_%E8%B3%87%E6%96%99%E6%95%B4%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [128]:
# 無意義資料:a(地址), AA12(無資料), bn(社區名), commid(社區ID), id(排序ID),  pimg(照片), sq(一串不明意義文字)
# 缺失值太多, "cp", "es", "mark", "note", "punit", "reid"
# 要預測資料：p -> 每坪單價, tp -> 總價
# 需切割資料:f(樓層/總樓層), v(?房?廳?衛)

In [129]:
import requests
import csv
import codecs
import pandas as pd
import json
from urllib.request import urlretrieve

url = requests.get("https://lvr.land.moi.gov.tw/SERVICE/QueryPrice/a0388809ef58d3752bcdb4177d0d894e", params = 
                  {"q":"VTJGc2RHVmtYMS9ERUNtNFRFcmVpcTl5K2hsdzgxNDdETHQ5OGFvTm0yZy8rZUlkNW5ZVTVLYTJlT09kcnNmei9OTG02WlYzTks5dGxFM01XcDU2ZzNvenkwcGE4NHJQdGcvRjUvc3I0Z0R2M3N0VHFETThZR3RnZDhoT0RIam9COGsxOUFOV3lPeEQvWkNHSDdvSllFaWt1aTgyRjhQbkJxN0dRTzl5VnBrYUVXelhaUUFqczdQK3ZQWW81ZjNZUW54b1JBNkc1OHlQdUR6T0ZUT3oxWUR2czdZdFB4ZWl3S293bmU5TnpQaXlacjJGeUhibFRyRC82bTNpUUNONjd5c3ZCeWREaS94K3hjclEwN2NQNlkydjgzUWpLdWNKbkF2dzRqaE1ZZWpBQ2hmRVpmWVZ0dUFoQTB3bzNxTTJnR2huWFZBWHhTYzFjbHFmTjhnbzBVSFREVWtMTVJQblpLK3V1NW42ZnFNUFZjTE1TeEh6aWdDY3ZNZlpxUFVSMmpsL3htUmIrVW81eEhhSHorUTdnUVdPV0Flb1paU2VoY3grRWY2c1V0MnBVNVdZbUhYVW1YOFBmWWNYYVBoOVpOb25OTkdzeE9tc1ByRElhc3pybnBnYzJZSE1kYmVWaDBwVnBBQVZDNzEwT0xVV1Y5NzhVa1VsaFFTUVRVdGlwNm5zeXpQbkxWa282TExLWXZZaUVjaTk2Zm1xZVEyUk5kMFFIYXA4UzZsazduS244Z2JKdVVTbHE3ZTZCT3hLQk9zTHVac1BtTlNyWHN1a0ZNa05hMUdRWHdNa08xRW4zam1pMHFRb3FjTit5aU82UHk2OUIxRlM0RjQvY0FBRWxGTlczU2NqZk8xTWFSYTBsQzRhWGVNYmVIWTY1SXJ6cWdMQ1RFT1BpUVNvSWdVaDVwdEV2OXk4eHhmV3JEQVg="})

data_shilin = url.json()

# with open("shilin_house.json") as f:
#   data_shilin = json.load(f)

# data_shilin

" 資料保存 "
# json 檔
with codecs.open("shilin_111_house.json", "w", encoding = "utf8") as f:
  f.write(json.dumps(data_shilin, indent=2, ensure_ascii=False))

In [130]:
df = pd.DataFrame(data_shilin, columns = data_shilin[0])
df

,AA11,AA12,a,b,bn,bs,city,commid,cp,e,el,es,f,fi,g,id,j,k,l,lat,lon,m,mark,msg,note,p,pimg,pu,punit,r,reid,s,sq,t,tp,tunit,twn,type,unit,v
0,住,,延平北路六段１１６巷００２弄０００８號三樓#延平北路六段１１６巷２弄８號三樓,公寓(5樓含以下無電梯),,87.39%,A,,,111/10/03,無,,三層/四層,,41,0,1,1,0,25.089290,121.508230,無,,總價/總面積,,"330,711",bt_01.png,住家用,1,28,,22.68,3B6lCDKhwEHTlclyWe8IgI9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"7,500,000",1,A15,Biz,2,3房1廳2衛
1,住,,永平街０３６巷０００４號二樓#永平街３６巷４號二樓,公寓(5樓含以下無電梯),,82.82%,A,,,111/09/15,無,,二層/四層,,42,1,1,1,0,25.090464,121.505469,無,,總價/總面積,親友、員工、共有人或其他特殊關係間之交易;,"314,218",bt_01.png,住家用,1,28,,21.15,4+0rROBjBB4ZlT6Lb0LQn49zgjWI96otsv8AEWcEUys=,房地(土地+建物),"6,645,000",1,A15,Biz,2,2房2廳2衛
2,住,,忠義街０７８巷０００７號四樓#忠義街７８巷７號四樓,公寓(5樓含以下無電梯),,86.80%,A,,,111/09/01,無,,四層/五層,-1,43,2,1,1,0,25.106244,121.531630,無,,總價/總面積,,"607,260",bt_01.png,住家用,1,32,,30.46,MdflpIvgaNAzZHSf+7nW5o9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"18,500,000",1,A15,Biz,2,3房2廳1衛
3,其他,,雨農路００６４號三樓之１#雨農路６４號三樓之１,住宅大樓(11層含以上有電梯),雨農山莊,52.85%,A,jZ3rTnKy659aSQWh5eKScI9zgjWI96otsv8AEWcEUys=,,111/09/10,有,,三層/十二層,,17,3,1,1,1,25.099639,121.533347,有,,總價/總面積,陽台加窗。\n車位資訊：地下一層或地下二層(需定期抽籤),"558,354",bt_05.png,住家用,1,104,,60.68,jZ3rTnKy659aSQWh5eKScI9zgjWI96otsv8AEWcEUys=,房地(土地+建物)+車位,"33,880,000",1,A15,Biz,2,3房2廳2衛
4,住,,通河西街二段１０８巷０００７號三樓#通河西街二段１０８巷７號三樓,公寓(5樓含以下無電梯),,87.26%,A,,,111/09/30,無,,三層/四層,,47,4,1,1,0,25.092406,121.507896,無,,總價/總面積,,"393,547",bt_01.png,住家用,1,11,,24.14,I+zjXvFvNTi9Ter0nQs1kI9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"9,500,000",1,A15,Biz,2,1房1廳1衛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,住,,中山北路七段１９０巷００２７號地下一層#中山北路七段１９０巷２７號地下一層,華廈(10層含以下有電梯),翠林大廈,100.00%,A,YJI3GdKlwTSLtUfojRhc4iFgKq1IoxSo3lGw6aX4bl8=,,111/01/16,有,,地下一層/七層,-1,42,984,1,1,0,25.126048,121.535226,有,,總價/總面積,,"90,678",bt_06.png,其他,1,20,,33.08,YJI3GdKlwTSLtUfojRhc4iFgKq1IoxSo3lGw6aX4bl8=,房地(土地+建物),"3,000,000",1,A15,Biz,2,0房1廳0衛
985,住,,忠誠路二段０８２巷０００１號三樓#忠誠路二段８２巷１號三樓,公寓(5樓含以下無電梯),,100.00%,A,,,111/01/12,無,,三層/四層,-1,47,985,1,1,0,25.112558,121.530616,無,,總價/總面積,親友、員工、共有人或其他特殊關係間之交易;,"615,101",bt_01.png,住家用,1,14,,26.01,GFk0bn/hqa/cc0pSzHpvtY9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"16,000,000",1,A15,Biz,2,2房2廳1衛
986,住,,重慶北路四段００８１號二樓之２#重慶北路四段８１號二樓之２,華廈(10層含以下有電梯),台北市大興,78.55%,A,hOr+w0Tqgsr11SiT8N5DhY9zgjWI96otsv8AEWcEUys=,,111/01/20,有,,二層/七層,-1,43,986,1,1,0,25.081422,121.512361,有,,總價/總面積,,"443,035",bt_06.png,住家用,1,57,,42.43,hOr+w0Tqgsr11SiT8N5DhY9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"18,800,000",1,A15,Biz,2,1房1廳1衛
987,住,,中山北路六段００２巷００５３號四樓#中山北路六段２巷５３號四樓,公寓(5樓含以下無電梯),,84.89%,A,,,111/01/01,無,,四層/五層,-1,38,987,1,1,0,25.103837,121.528298,無,,總價/總面積,親友、員工、共有人或其他特殊關係間之交易;,"359,521",bt_01.png,住家用,1,28,,33.38,sZ682TQ8Spg1NM1ZCy1GfY9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"12,000,000",1,A15,Biz,2,3房1廳2衛
988,商,,天母東路０４３巷００４弄０００９號二樓#天母東路４３巷４弄９號二樓,華廈(10層含以下有電梯),伉儷園,84.49%,A,aSxewFiJLxtCUB84DIF5fY9zgjWI96otsv8AEWcEUys=,,111/01/17,有,,二層/七層,-1,42,988,1,1,0,25.118690,121.532755,無,,總價/總面積,出售持分為2分之1親友、員工、共有人或其他特殊關係間之交易;,"721,805",bt_06.png,住家用,1,38,,22.72,aSxewFiJLxtCUB84DIF5fY9zgjWI96otsv8AEWcEUys=,房地(土地+建物),"16,400,000",1,A15,Biz,2,3房2廳2衛

In [131]:
df = pd.DataFrame(data_shilin, columns = data_shilin[0]) # pandas的表個型態
df = df.drop(["a", "AA12", "bn", "commid", "id", "pimg", "sq", "cp", "es", "mark", "note", "punit", "reid"], axis = 1)

# df["ans"] = data_shilin["p"] # 看要預測單價或總價
# df["ans"] = data_shilin["tp"] # 看要預測單價或總價

pd.set_option('display.max_columns', 500)
df

# 無意義資料:a(地址), AA12(無資料), bn(社區名), commid(社區ID), id(排序ID), lat(經度), lon(緯度),  pimg(照片), sq(一串不明意義文字) delete complete
# 缺失值太多, "cp", "es", "mark", "note", "punit", "reid" delete complete

,AA11,b,bs,city,e,el,f,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,v
0,住,公寓(5樓含以下無電梯),87.39%,A,111/10/03,無,三層/四層,,41,1,1,0,25.089290,121.508230,無,總價/總面積,"330,711",住家用,28,22.68,房地(土地+建物),"7,500,000",1,A15,Biz,2,3房1廳2衛
1,住,公寓(5樓含以下無電梯),82.82%,A,111/09/15,無,二層/四層,,42,1,1,0,25.090464,121.505469,無,總價/總面積,"314,218",住家用,28,21.15,房地(土地+建物),"6,645,000",1,A15,Biz,2,2房2廳2衛
2,住,公寓(5樓含以下無電梯),86.80%,A,111/09/01,無,四層/五層,-1,43,1,1,0,25.106244,121.531630,無,總價/總面積,"607,260",住家用,32,30.46,房地(土地+建物),"18,500,000",1,A15,Biz,2,3房2廳1衛
3,其他,住宅大樓(11層含以上有電梯),52.85%,A,111/09/10,有,三層/十二層,,17,1,1,1,25.099639,121.533347,有,總價/總面積,"558,354",住家用,104,60.68,房地(土地+建物)+車位,"33,880,000",1,A15,Biz,2,3房2廳2衛
4,住,公寓(5樓含以下無電梯),87.26%,A,111/09/30,無,三層/四層,,47,1,1,0,25.092406,121.507896,無,總價/總面積,"393,547",住家用,11,24.14,房地(土地+建物),"9,500,000",1,A15,Biz,2,1房1廳1衛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,住,華廈(10層含以下有電梯),100.00%,A,111/01/16,有,地下一層/七層,-1,42,1,1,0,25.126048,121.535226,有,總價/總面積,"90,678",其他,20,33.08,房地(土地+建物),"3,000,000",1,A15,Biz,2,0房1廳0衛
985,住,公寓(5樓含以下無電梯),100.00%,A,111/01/12,無,三層/四層,-1,47,1,1,0,25.112558,121.530616,無,總價/總面積,"615,101",住家用,14,26.01,房地(土地+建物),"16,000,000",1,A15,Biz,2,2房2廳1衛
986,住,華廈(10層含以下有電梯),78.55%,A,111/01/20,有,二層/七層,-1,43,1,1,0,25.081422,121.512361,有,總價/總面積,"443,035",住家用,57,42.43,房地(土地+建物),"18,800,000",1,A15,Biz,2,1房1廳1衛
987,住,公寓(5樓含以下無電梯),84.89%,A,111/01/01,無,四層/五層,-1,38,1,1,0,25.103837,121.528298,無,總價/總面積,"359,521",住家用,28,33.38,房地(土地+建物),"12,000,000",1,A15,Biz,2,3房1廳2衛
988,商,華廈(10層含以下有電梯),84.49%,A,111/01/17,有,二層/七層,-1,42,1,1,0,25.118690,121.532755,無,總價/總面積,"721,805",住家用,38,22.72,房地(土地+建物),"16,400,000",1,A15,Biz,2,3房2廳2衛

In [132]:
" 分割 f "
" 取得購買的第一樓層 "
def change(n1):
  if pd.isna(n1):
    return n1
  else:
    x = n1.split("/")[0].strip()
    if x.find(",") != -1:
      return x.split(",")[0].strip()
    else:
      return x

df["flr"] = df["f"].apply(change)

" 額外的第二樓層 "
df["flr"] = df["f"].apply(change)
df_flr = df["flr"].unique()

def change(n2):
  if pd.isna(n2):
    return n2
  else:
    x = n2.split("/")[0].strip()
    if (x.find(",") != -1):
      return x.split(",")[1]
    else:
      return None

df["extraflr"] = df["f"].apply(change)

" 額外的第三樓層 "
def change(n3):
  if pd.isna(n3):
    return n3
  else:
    x = n3.split("/")[0].strip()
    if (x.find(",") != -1):
      if len(x.split(",")) >= 3:
        return x.split(",")[2]
      else:
        return None
    else:
      return None
df["2extraflr"] = df["f"].apply(change)

" 額外的第四樓層 "
def change(n4):
  if pd.isna(n4):
    return n4
  else:
    x = n4.split("/")[0].strip()
    if (x.find(",") != -1):
      if len(x.split(",")) >= 3:
        if len(x.split(",")) >= 4:
          return x.split(",")[3]
        else:
          return None
      else:
        return None
    else:
      return None

df["3extraflr"] = df["f"].apply(change)

" 總樓層 "
def change(s):
  if pd.isna(s):
    return s
  else:
    return s.split("/")[1].strip()
df["totalflr"] = df["f"].apply(change)
df_totalflr = df["totalflr"].unique()
df_totalflr

array(['四層', '五層', '十二層', '六層', '十三層', '十一層', '八層', '二層', '十四層', '十八層',
       '三層', '七層', '二十一層', '九層', '--', '十五層', '十層', '十六層', '一層', '二十四層',
       '三十八層', '二十二層', '十九層', '十七層'], dtype=object)

In [133]:
" 確認樓層分割狀況 "
# totalflr_unique.sort_values(ascending = True)
# df_totalflr = df["totalflr"].value_counts()
# df_totalflr

# 需切割資料:f(樓層/總樓層) delete complete

' 確認樓層分割狀況 '

In [134]:
" v 切割(?房?廳?衛) " # 先切?房
def change(r1):
  if pd.isna(r1):
    return r1
  else:
    return r1.split("房")[0]
df["room"] = df["v"].apply(change)

# 再切廳
def change(r2):
  if pd.isna(r2):
    return r2
  else:
    return r2.split("廳")[0].split("房")[-1]
df["office"] = df["v"].apply(change)

# 再切衛
def change(r3):
  if pd.isna(r3):
    return r3
  else:
    return r3.split("廳")[-1].split("衛")[0]
df["toilet"] = df["v"].apply(change)

# 需切割資料:v(?房?廳?衛) depart complete

In [135]:
" 貨幣轉換 "
# tp & p 有 ',', 不為數值
def change(x): 
    if pd.isna(x):
        return x
    else:
        return x.replace(",","")
    
df["tp"] = df["tp"].apply(lambda x:change(x))

def change(x2): 
    if pd.isna(x2):
        return x2
    else:
        return x2.replace(",","")
    
df["p"] = df["p"].apply(change)

In [136]:
" 日期轉換 "
def change(d): 
    if pd.isna(d):
        return d
    else:
        d = str(int(d.split("/")[0]) + 1911) + "-" + d.split("/")[1] + "-" + d.split("/")[2]
        return d   
df["e"] = df["e"].apply(change)
df["e"] = pd.to_datetime(df['e'], errors = 'coerce')

In [137]:
" 確認是否有 異常 存在 "
# df["tp"] = df["tp"].astype(float)

# df_tp = df["tp"].unique()
# df_tp_counts = df["tp"].value_counts()
# print(df_tp)
# print(df_tp_counts)

# # 數據概況
# print(df.describe())

# # 前?行資訊
# print(df.head(60))

# # 60~120行資訊
# print(df[60:120])

# df

' 確認是否有 異常 存在 '

In [138]:
" bs 有 %, 無法做 median, 先分割 "
def change(m):
  if pd.isna(m):
    return m
  else:
    return m.split("%")[0]
df["bs"] = df["bs"].apply(change)

In [139]:
" 樓層名轉換數值"
# 類別值:AA11, b, city, el, m, msg, pu, t, twn, type
# 未知定義, 先當類別:el, m

column_dict = {"--":None,"":None,None:0, '陽台':1, '平台':1, '屋頂突出物':1, '夾層':1, '電梯樓梯間':1, '騎樓':1, '陽臺':1, '地下一層':0, '地下層':0, '全':100, '一層':1, '二層':2, '三層':3, '四層':4, '五層':5, '六層':6, '七層':7, '八層':8, '九層':9, '十層':10, '十一層':11, '十二層':12, '十三層':13, '十四層':14, '十五層':15, '十六層':16, '十七層':17, '十八層':18, '十九層':19, '二十層':20, '二十一層':21, '二十二層':22, '二十三層':23, '二十四層':24, '二十五層':25, '二十六層':26, '二十七層':27, '二十八層':28, '二十九層':29, '三十層':30, '三十一層':31, '三十二層':32, '三十三層':33, '三十四層':34, '三十五層':35, '三十六層':36, '三十七層':37, '三十八層':38, '三十九層':39, '四十層':40, '四十一層':41, '四十二層':42, '四十三層':43, '四十四層':44, '四十五層':45, '四十六層':46, '四十七層':47, '四十八層':48, '四十九層':49, '五十層':50}

df = df.replace({"flr": column_dict})
df = df.replace({"extraflr": column_dict})
df = df.replace({"2extraflr": column_dict})
df = df.replace({"3extraflr": column_dict})
df = df.replace({"totalflr": column_dict})
df = df.replace({"pu": column_dict})

" 將 "" 轉換空值 "
# 數值:bs, e, g, j, k, l, lat, lon, s, flr, extraflr, 2extraflr, 3extraflr, totlaflr, room, offic, toilet
# 未知定義, 先當數值:fi, r, tunit, unit

column_sort_dict = {"":None}

df = df.replace({"bs": column_sort_dict})
df = df.replace({"e": column_sort_dict})
df = df.replace({"g": column_sort_dict})
df = df.replace({"j": column_sort_dict})
df = df.replace({"l": column_sort_dict})
df = df.replace({"fi": column_sort_dict})
df = df.replace({"room": column_sort_dict})
df = df.replace({"office": column_sort_dict})
df = df.replace({"toilet": column_sort_dict})

df = df.drop(["f", "v"], axis = 1) # 難分辨資料已分割, 去除該資料
df

,AA11,b,bs,city,e,el,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,flr,extraflr,2extraflr,3extraflr,totalflr,room,office,toilet
0,住,公寓(5樓含以下無電梯),87.39,A,2022-10-03,無,None,41,1,1,0,25.089290,121.508230,無,總價/總面積,330711,住家用,28,22.68,房地(土地+建物),7500000,1,A15,Biz,2,3,0,0,0,4.0,3,1,2
1,住,公寓(5樓含以下無電梯),82.82,A,2022-09-15,無,None,42,1,1,0,25.090464,121.505469,無,總價/總面積,314218,住家用,28,21.15,房地(土地+建物),6645000,1,A15,Biz,2,2,0,0,0,4.0,2,2,2
2,住,公寓(5樓含以下無電梯),86.80,A,2022-09-01,無,-1,43,1,1,0,25.106244,121.531630,無,總價/總面積,607260,住家用,32,30.46,房地(土地+建物),18500000,1,A15,Biz,2,4,0,0,0,5.0,3,2,1
3,其他,住宅大樓(11層含以上有電梯),52.85,A,2022-09-10,有,None,17,1,1,1,25.099639,121.533347,有,總價/總面積,558354,住家用,104,60.68,房地(土地+建物)+車位,33880000,1,A15,Biz,2,3,0,0,0,12.0,3,2,2
4,住,公寓(5樓含以下無電梯),87.26,A,2022-09-30,無,None,47,1,1,0,25.092406,121.507896,無,總價/總面積,393547,住家用,11,24.14,房地(土地+建物),9500000,1,A15,Biz,2,3,0,0,0,4.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,住,華廈(10層含以下有電梯),100.00,A,2022-01-16,有,-1,42,1,1,0,25.126048,121.535226,有,總價/總面積,90678,其他,20,33.08,房地(土地+建物),3000000,1,A15,Biz,2,0,0,0,0,7.0,0,1,0
985,住,公寓(5樓含以下無電梯),100.00,A,2022-01-12,無,-1,47,1,1,0,25.112558,121.530616,無,總價/總面積,615101,住家用,14,26.01,房地(土地+建物),16000000,1,A15,Biz,2,3,0,0,0,4.0,2,2,1
986,住,華廈(10層含以下有電梯),78.55,A,2022-01-20,有,-1,43,1,1,0,25.081422,121.512361,有,總價/總面積,443035,住家用,57,42.43,房地(土地+建物),18800000,1,A15,Biz,2,2,0,0,0,7.0,1,1,1
987,住,公寓(5樓含以下無電梯),84.89,A,2022-01-01,無,-1,38,1,1,0,25.103837,121.528298,無,總價/總面積,359521,住家用,28,33.38,房地(土地+建物),12000000,1,A15,Biz,2,4,0,0,0,5.0,3,1,2
988,商,華廈(10層含以下有電梯),84.49,A,2022-01-17,有,-1,42,1,1,0,25.118690,121.532755,無,總價/總面積,721805,住家用,38,22.72,房地(土地+建物),16400000,1,A15,Biz,2,2,0,0,0,7.0,3,2,2

In [140]:
df
df.isna() # 確認哪些是空值
s = df.isna().sum() # 確認每欄有幾個空值
s[s > 0]

bs          51
fi          71
g           22
pu           2
totalflr     8
room        59
office      59
toilet      59
dtype: int64

In [141]:
" 補類別值 "
# 自認非空值, 待補類別值 pu

# df["pu"].value_counts() # 取得 pu 欄位內值的數量
# df["pu"].value_counts().max() # 取得 pu 類別內數量最多的數量
mostidx = df["pu"].value_counts().idxmax() # 取得 pu 內最多數量的值

df["pu"] = df["pu"].fillna(mostidx) # fillna 空值欄填入資料, mostidx 為[(最多的類別)的值]

In [142]:
" 補數值 "
# 自認非空值, 待補數值 bs, fi, g, room, office, toilet

df.median() 

bs_med = df["bs"].median()
df["bs"] = df["bs"].fillna(bs_med)

fi_med = df["fi"].median()
df["fi"] = df["fi"].fillna(fi_med)

g_med = df["g"].median()
df["g"] = df["g"].fillna(g_med)

totalflr_med = df["totalflr"].median()
df["totalflr"] = df["totalflr"].fillna(totalflr_med)

room_med = df["room"].median()
df["room"] = df["room"].fillna(room_med)

office_med = df["office"].median()
df["office"] = df["office"].fillna(office_med)

toilet_med = df["toilet"].median()
df["toilet"] = df["toilet"].fillna(toilet_med)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.

In [143]:
df
df.isna() # 確認哪些是空值
s = df.isna().sum() # 確認每欄有幾個空值
# s
s[s > 0]

Series([], dtype: int64)

In [144]:
" 資料保存 "

# CSV 檔
df.to_csv( "shilin_111_house.csv"  , index=False )