<a href="https://colab.research.google.com/github/Liang130520/Tibame-TeamProject/blob/main/TeamProject_api_7%E7%89%88_%E5%8F%B0%E5%8C%97%E5%B8%82all_%E6%AD%A3%E8%A6%8F%E5%8C%96%E8%99%95%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
" 抓取資料 "
import csv
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
data_shilin = pd.read_csv("/content/drive/MyDrive/台北市房屋交易_all.csv", encoding = "utf-8")
pd.set_option('display.max_columns', 500)
data_shilin

In [ ]:
" 轉換文件名稱 "
df = pd.DataFrame(data_shilin, columns = data_shilin.columns)

In [ ]:
" 取得 column 下的 NAN 數量 "
df.isna().sum()

In [ ]:
" 刪除不必要資訊 "
df = df.drop(["建築完成年月"], axis = 1) # NAN 值過多, 會擴大原先差異
df = df.drop(["土地位置建物門牌","緯度","經度"], axis = 1) # 干擾分析的因素
df
# df.isna().sum()

In [ ]:
" 取得類別值最常出現的數 "
# df["建築完成年月"].value_counts() # 取得 Embarked 欄位內值的數量
# df["建築完成年月"].value_counts().max() # 取得 Embarked 類別內數量最多的數量
# mostidx = df["建築完成年月"].value_counts().idxmax() # 取得 Embarked 內最多數量的值
# mostidx
# df["建築完成年月"].value_counts()
" 更改類別值 column 下的 NAN 值 "
# df["建築完成年月"] = df["建築完成年月"].fillna(mostidx)

' 更改類別值 column 下的 NAN 值 '

類別值:鄉鎮市區、交易標的、都市土地使用分區、建物型態、主要用途、主要建材、有無管理組織、車位類別、電梯

In [ ]:
""" One-Hot Encoding """
df = pd.get_dummies(df)
df = pd.get_dummies(df, columns = ["有無管理組織","電梯"])
# df

In [ ]:
" 取得數值類中位數 "
med = df.median()
med
""" 更改數值 column 下的 NAN 值 """
df = df.fillna(med)

數值:土地移轉總面積平方公尺、建物移轉總面積平方公尺、總價元、單價元平方公尺、車位移轉總面積(平方公尺)、車位總價元、主建物面積、附屬建物面積、陽台面積、所得中位數

下方：標準化, 取極值, 並捨去

In [ ]:
" 載入程式 "
# !pip install sklearn
from sklearn.preprocessing import StandardScaler
from math import sqrt

# 做出 idx 的Series, 方便後面刪除 row
dic = pd.Series({"idx":[]})

In [ ]:
""" 土地移轉總面積平方公尺 標準化 """
# 資料標準差前置
values = df['土地移轉總面積平方公尺'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['土地移轉總面積平方公尺'])):
  if (abs(df["土地移轉總面積平方公尺"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

29.250512166071125 89.54619680488135

In [ ]:
""" 建物移轉總面積平方公尺 標準化 """

# 資料標準差前置
values = df['建物移轉總面積平方公尺'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['建物移轉總面積平方公尺'])):
  if (abs(df["建物移轉總面積平方公尺"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

131.33730729964267 423.4550904047903

In [ ]:
""" 總價元 標準化 """

# 資料標準差前置
values = df['總價元'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['總價元'])):
  if (abs(df["總價元"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

27382453.928705122 93137341.6950428

In [ ]:
""" 單價元平方公尺 標準化 """

# 資料標準差前置
values = df['單價元平方公尺'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['單價元平方公尺'])):
  if (abs(df["單價元平方公尺"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

209065.73855708694 124223.33041529976

In [ ]:
""" 車位移轉總面積(平方公尺) 標準化 """

# 資料標準差前置
values = df['車位移轉總面積(平方公尺)'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['車位移轉總面積(平方公尺)'])):
  if (abs(df["車位移轉總面積(平方公尺)"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

8.0266539050536 23.084910722984127

In [ ]:
""" 車位總價元 標準化 """

# 資料標準差前置
values = df['車位總價元'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['車位總價元'])):
  if (abs(df["車位總價元"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

507783.58099370426 1766404.0285600221

In [ ]:
""" 主建物面積 標準化 """

# 資料標準差前置
values = df['主建物面積'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['主建物面積'])):
  if (abs(df["主建物面積"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

85.871842776927 212.7883073603531

In [ ]:
""" 附屬建物面積 標準化 """

# 資料標準差前置
values = df['附屬建物面積'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['附屬建物面積'])):
  if (abs(df["附屬建物面積"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

3.3918768078951844 35.364346635638505

In [ ]:
""" 陽台面積 標準化 """

# 資料標準差前置
values = df['陽台面積'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['陽台面積'])):
  if (abs(df["陽台面積"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

7.205479836651352 10.319330588583307

In [ ]:
""" 所得中位數 標準化 """

# 資料標準差前置
values = df['所得中位數'].values
values = values.reshape((len(values), 1))
# 計算標準差
scaler = StandardScaler()
scaler = scaler.fit(values)
# 取平均數
avg = float(scaler.mean_)  
# 取標準差
standard = sqrt(scaler.var_)  
print(avg, standard)

" 抓取 2.5% 極值資料 "
for i in range(len(df['所得中位數'])):
  if (abs(df["所得中位數"][i] - avg) >= standard * 3):
    if i in dic["idx"]:
      pass
    else:
      dic["idx"].append(i)
  else:
    pass

" 確認 2.5% 極值資料 "
for j in dic["idx"]:  
  df[j:j+1]

570148.2048664284 66897.01770105127

In [ ]:
""" 確認 idx 是否有相撞 """
# dic = dic.apply(sorted).transform(tuple).unique()
# dic = dic.unique
dic

idx    [11, 751, 1079, 1576, 2273, 2538, 2776, 3062, ...
dtype: object

In [ ]:
" 刪除 2.5% 極值資料 "
for j in dic[0]:
  df = df.drop(index = j)

#### Max Min 正規化處理

In [ ]:
""" Max Min 正規化處理 """
from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler()

In [ ]:
" 總價元 Max Min 正規化處理 "
values = df['總價元'].values
values = values.reshape((len(values), 1))
df["總價元"] = minmax.fit_transform(values)

In [ ]:
" 單價元平方公尺 Max Min 正規化處理 "
values = df['單價元平方公尺'].values
values = values.reshape((len(values), 1))
df["單價元平方公尺"] = minmax.fit_transform(values)

In [ ]:
" 所得中位數 Max Min 正規化處理 "
values = df['所得中位數'].values
values = values.reshape((len(values), 1))
df["所得中位數"] = minmax.fit_transform(values)

In [ ]:
df

,土地移轉總面積平方公尺,交易年月日,移轉層次,總樓層數,建物移轉總面積平方公尺,建物現況格局-房,建物現況格局-廳,建物現況格局-衛,建物現況格局-隔間,總價元,單價元平方公尺,車位移轉總面積(平方公尺),車位總價元,主建物面積,附屬建物面積,陽台面積,交易年,建築年,屋齡,年平均CPI,CPI年增率,所得中位數,鄉鎮市區_中山區,鄉鎮市區_中正區,鄉鎮市區_信義區,鄉鎮市區_內湖區,鄉鎮市區_北投區,鄉鎮市區_南港區,鄉鎮市區_士林區,鄉鎮市區_大同區,鄉鎮市區_大安區,鄉鎮市區_文山區,鄉鎮市區_松山區,鄉鎮市區_萬華區,交易標的_建物,交易標的_房地(土地+建物),交易標的_房地(土地+建物)+車位,都市土地使用分區_住,都市土地使用分區_其他都市土地使用分區,都市土地使用分區_商,建物型態_住宅大樓(11層含以上有電梯),建物型態_公寓(5樓含以下無電梯),建物型態_套房(1房1廳1衛),建物型態_店面(店鋪),建物型態_廠辦,建物型態_華廈(10層含以下有電梯),建物型態_透天厝,主要用途_住商用,主要用途_住家用,主要用途_住工用,主要用途_其他用途,主要用途_商業用,主要用途_工業用,主要用途_辦公用,主要用途_農業用,主要建材_其他主要建材,主要建材_加強磚造,主要建材_鋼筋混凝土造,主要建材_鋼骨造,主要建材_鋼骨鋼筋混凝土造,車位類別_一樓平面,車位類別_其他車位類別,車位類別_升降平面,車位類別_升降機械,車位類別_坡道平面,車位類別_坡道機械,車位類別_塔式車位,車位類別_無車位,有無管理組織_0,有無管理組織_1,電梯_0.0,電梯_1.0
0,22.50,1110206,1,4,68.61,2,1,1,1,0.032669,0.251648,0.00,0,68.61,0.00,0.00,111,80,31,107.12,0.00,0.515504,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0
1,6.39,1110208,9,15,84.19,2,1,1,1,0.057767,0.362580,0.00,0,51.78,2.65,0.00,111,101,10,107.12,0.00,0.000000,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1
2,9.35,1110210,6,10,38.90,0,0,0,0,0.031688,0.430420,0.00,0,19.92,0.56,3.38,111,90,21,107.12,0.00,0.468992,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1
3,22.91,1110209,9,13,143.46,3,2,2,1,0.078421,0.288844,0.00,0,85.25,4.06,6.64,111,102,9,107.12,0.00,0.313953,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1
4,22.81,1110210,3,14,132.11,2,1,1,1,0.064695,0.258750,43.40,0,54.23,2.17,3.69,111,97,14,107.12,0.00,0.515504,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11748,27.81,1100331,11,12,185.86,2,2,1,1,0.205873,0.585245,0.00,0,163.64,0.00,0.00,110,62,48,104.32,1.96,1.000000,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1
11749,34.03,1100311,3,5,113.39,3,2,2,1,0.052930,0.246674,0.00,0,100.68,0.00,12.71,110,69,41,104.32,1.96,0.569767,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0
11750,22.19,1090928,3,13,183.46,3,2,2,1,0.098029,0.282333,41.72,0,85.72,0.31,8.83,109,98,11,102.31,-0.23,0.468992,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1
11751,3.92,1090731,10,14,38.09,0,0,0,0,0.035754,0.496076,0.00,0,33.89,0.00,0.00,109,65,44,102.31,-0.23,1.000000,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1
11752,12.75,1090524,4,4,38.93,1,1,1,1,0.013061,0.177403,0.00,0,38.93,0.00,0.00,109,58,51,102.31,-0.23,0.515504,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0

In [ ]:
df.to_csv("台北市房屋交易_all_standard&Normal.csv", encoding = "utf-8")