<a href="https://colab.research.google.com/github/Liang130520/Tibame-TeamProject/blob/main/TeamProject_api_%E6%A8%A1%E5%9E%8B_1%E7%89%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd
from urllib.request import urlretrieve
from sklearn.datasets import load_boston

# url = "http://lib.stat.cmu.edu/datasets/boston"
# urlretrieve(url, "test.csv")

shilin_data = pd.read_csv("shilin_house.csv", encoding = "utf-8")
df = pd.DataFrame(shilin_data)
df["ans"] = df["tp"]

pd.set_option('display.max_columns', 500)
df

,AA11,b,bs,city,e,el,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,flr,extraflr,2extraflr,3extraflr,totalflr,room,office,toilet,ans
0,住,公寓(5樓含以下無電梯),87.39,A,111/10/03,無,-1.0,41.0,1,1,0,25.089290,121.508230,無,總價/總面積,330711.0,住家用,28,22.68,房地(土地+建物),7500000,1,A15,Biz,2,3,0,0,0,4.0,3.0,1.0,2.0,7500000
1,住,華廈(10層含以下有電梯),65.01,A,111/09/08,有,-1.0,21.0,1,1,0,25.099083,121.529616,有,總價/總面積,926460.0,住家用,51,29.52,房地(土地+建物),27350000,1,A15,Biz,2,6,0,0,0,6.0,3.0,2.0,2.0,27350000
2,住,公寓(5樓含以下無電梯),82.82,A,111/09/15,無,-1.0,42.0,1,1,0,25.090464,121.505469,無,總價/總面積,314218.0,住家用,28,21.15,房地(土地+建物),6645000,1,A15,Biz,2,2,0,0,0,4.0,2.0,2.0,2.0,6645000
3,工,住宅大樓(11層含以上有電梯),50.14,A,111/09/05,有,-1.0,15.0,1,1,1,25.088385,121.516940,有,(總價-車位總價)/(總面積-車位總面積),618304.0,商業用,73,43.39,房地(土地+建物)+車位,21500000,1,A15,Biz,2,8,0,0,0,14.0,3.0,2.0,2.0,21500000
4,住,公寓(5樓含以下無電梯),100.00,A,111/09/17,無,-1.0,48.0,1,1,0,25.108141,121.523815,無,總價/總面積,612635.0,住家用,31,28.57,房地(土地+建物),17500000,1,A15,Biz,2,2,0,0,0,4.0,3.0,2.0,2.0,17500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,華廈(10層含以下有電梯),44.01,A,110/10/08,有,-1.0,3.0,1,1,1,25.100296,121.523722,有,總價/總面積,627474.0,住家用,25,45.90,房地(土地+建物)+車位,28800000,1,A15,Biz,2,7,0,0,0,9.0,3.0,2.0,2.0,28800000
1472,住,公寓(5樓含以下無電梯),81.31,A,110/10/30,無,-1.0,43.0,1,1,0,25.088497,121.505272,無,總價/總面積,404129.0,住家用,24,24.74,房地(土地+建物),10000000,1,A15,Biz,2,3,0,0,0,5.0,3.0,2.0,1.0,10000000
1473,商,華廈(10層含以下有電梯),88.88,A,110/10/27,有,-1.0,35.0,2,1,0,25.118698,121.525476,有,總價/總面積,527537.0,住家用,46,28.81,房地(土地+建物),15200000,1,A15,Biz,2,3,0,0,0,7.0,3.0,1.0,2.0,15200000
1474,住,公寓(5樓含以下無電梯),90.75,A,110/10/29,無,-1.0,44.0,1,1,0,25.101006,121.529684,無,總價/總面積,580536.0,住家用,12,30.66,房地(土地+建物),17800000,1,A15,Biz,2,2,0,0,0,4.0,3.0,2.0,2.0,17800000
1475,住,住宅大樓(11層含以上有電梯),47.46,A,110/10/12,有,0.0,NaN,1,1,1,25.082847,121.523063,有,(總價-車位總價)/(總面積-車位總面積),784519.0,住家用,35,45.77,房地(土地+建物)+車位,32000000,1,A15,Biz,2,4,0,0,0,15.0,2.0,2.0,1.0,32000000

In [58]:
df = df.drop(["e"], axis = 1)
df

,AA11,b,bs,city,el,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,flr,extraflr,2extraflr,3extraflr,totalflr,room,office,toilet,ans
0,住,公寓(5樓含以下無電梯),87.39,A,無,-1.0,41.0,1,1,0,25.089290,121.508230,無,總價/總面積,330711.0,住家用,28,22.68,房地(土地+建物),7500000,1,A15,Biz,2,3,0,0,0,4.0,3.0,1.0,2.0,7500000
1,住,華廈(10層含以下有電梯),65.01,A,有,-1.0,21.0,1,1,0,25.099083,121.529616,有,總價/總面積,926460.0,住家用,51,29.52,房地(土地+建物),27350000,1,A15,Biz,2,6,0,0,0,6.0,3.0,2.0,2.0,27350000
2,住,公寓(5樓含以下無電梯),82.82,A,無,-1.0,42.0,1,1,0,25.090464,121.505469,無,總價/總面積,314218.0,住家用,28,21.15,房地(土地+建物),6645000,1,A15,Biz,2,2,0,0,0,4.0,2.0,2.0,2.0,6645000
3,工,住宅大樓(11層含以上有電梯),50.14,A,有,-1.0,15.0,1,1,1,25.088385,121.516940,有,(總價-車位總價)/(總面積-車位總面積),618304.0,商業用,73,43.39,房地(土地+建物)+車位,21500000,1,A15,Biz,2,8,0,0,0,14.0,3.0,2.0,2.0,21500000
4,住,公寓(5樓含以下無電梯),100.00,A,無,-1.0,48.0,1,1,0,25.108141,121.523815,無,總價/總面積,612635.0,住家用,31,28.57,房地(土地+建物),17500000,1,A15,Biz,2,2,0,0,0,4.0,3.0,2.0,2.0,17500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,華廈(10層含以下有電梯),44.01,A,有,-1.0,3.0,1,1,1,25.100296,121.523722,有,總價/總面積,627474.0,住家用,25,45.90,房地(土地+建物)+車位,28800000,1,A15,Biz,2,7,0,0,0,9.0,3.0,2.0,2.0,28800000
1472,住,公寓(5樓含以下無電梯),81.31,A,無,-1.0,43.0,1,1,0,25.088497,121.505272,無,總價/總面積,404129.0,住家用,24,24.74,房地(土地+建物),10000000,1,A15,Biz,2,3,0,0,0,5.0,3.0,2.0,1.0,10000000
1473,商,華廈(10層含以下有電梯),88.88,A,有,-1.0,35.0,2,1,0,25.118698,121.525476,有,總價/總面積,527537.0,住家用,46,28.81,房地(土地+建物),15200000,1,A15,Biz,2,3,0,0,0,7.0,3.0,1.0,2.0,15200000
1474,住,公寓(5樓含以下無電梯),90.75,A,無,-1.0,44.0,1,1,0,25.101006,121.529684,無,總價/總面積,580536.0,住家用,12,30.66,房地(土地+建物),17800000,1,A15,Biz,2,2,0,0,0,4.0,3.0,2.0,2.0,17800000
1475,住,住宅大樓(11層含以上有電梯),47.46,A,有,0.0,NaN,1,1,1,25.082847,121.523063,有,(總價-車位總價)/(總面積-車位總面積),784519.0,住家用,35,45.77,房地(土地+建物)+車位,32000000,1,A15,Biz,2,4,0,0,0,15.0,2.0,2.0,1.0,32000000

In [59]:
" 做 One_Hot Encoding "
# 類別值:AA11, b, city, el, m, msg, pu, t, twn, type
# 未知定義, 先當類別:el, m
pd.set_option('display.max_columns', 500)
df = pd.get_dummies(df)
# df = pd.get_dummies(df, columns = ["pu"])
df

import numpy as np
x = np.array(df.drop(['p','tp','ans'], axis = 1))
y = np.array(df["ans"])

from sklearn.model_selection import train_test_split
# [90%x, 10%x, 90%y, 10%y]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)

from sklearn.tree import DecisionTreeRegressor
reg = DecisionTreeRegressor(max_depth=5)
reg.fit(x_train, y_train)

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
plt.figure(figsize=(15, 15))
plot_tree(reg, 
     filled=True,
     max_depth=4)

from sklearn.metrics import r2_score
pre = reg.predict(x_test)
r2_score(y_test, pre)

ValueError: ignored