<a href="https://colab.research.google.com/github/Liang130520/Tibame-TeamProject/blob/main/Team_Project_predict_api_2%E7%89%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import requests
import csv
import codecs
import pandas as pd
from sklearn.datasets import load_boston
import json

url = requests.get("https://lvr.land.moi.gov.tw/SERVICE/QueryPrice/682df06cf19eff9d854d500b283b5dd9", params = 
                  {"q":"VTJGc2RHVmtYMThrUlJIdTRzYTRaTGI0UUZMVDNIQ3FQbUVIbUVxWG4wQVhERU43K2R5UCtJMWtMYVBmVHRNWU0yd1ZEYlBiaDhLSFQ2WHQ0RWgzeC9GU1F3OXBTQ1JkNXJtbnh6NCtpK0cwa2NiUGlpemlrKzQ0dFBiY2dJMkVJY2FJSHJzUWx4MEJrZ0l0bDE5RDVjOURJUlQ3STVIL0JIZzE1MlJJYVk1dVdGYjFnK1IvcEhjWU1vM2J6Wi9IY1p0U2N4RnJqTlNDcy9kOVBBZlo4b1RnQkRGQ3VtL3cyM3lkei8vVlptV21lbVNYcDNqbzFBTld4YlpnVnFuOHRTZVpGcG9Qdkd6a1V0VnpxVXNEOWR3M1N0bWxxWGduemhWTjJKM1JnZXZUSE9kWVhHLzVOVUFkd01JOTgyazdPVXV2WXY2SW5JK09VL1dPdk14dW5RVUpQZEthMEhOTG5BWWVRTnRtQ1IzaDFFQ3EzUno1U0ZuZllyMEJFNWxHaTZmZllna08rQ2drRFpnNE54cnV0ZDJVWDRnNDBFRXpNOU1xWmY1TlpOckppYVI3NVE1ckVTQ0FOV2l0MzZvTGdZU09qQmwwT3BYdjJJTWw3bnRMbzZNdlYxR2tDSHE5eU9kazU2NVZZVHVseWpJN01PemhKeFJ3L0FiSlc2Vzk3RkluS0Ftc2IzcGlyLzlaU1VKYXQzVDgvd05Icmo2bFhMUWN6TTRDSEJ4N2kzQXJtd1hFcC9FdksxU2Y1OHZqVTFyYlJmS3Jac0RrTm02YmIvbUYvNk5WNjRlMUVPdHhmWGZwZ3BVeDkydWF0N1c1T3NlbDlkUll5SU82U2t6ZXZLTUp2ajF3aHIvcm1QMG1rOGk4TmlWNkpkaFZUeXRwa3o2TVQ2dFQzTWwrMHpJWE1reUgrOGppeng4WDdzSXE="})
data_shilin = url.json()

# " 資料保存 "
# with codecs.open("shilin.json", "w", encoding = "utf8") as f:
#   f.write(json.dumps(data_shilin, indent=2, ensure_ascii=False))

data_shilin


df = pd.DataFrame(data_shilin, columns = data_shilin[0]) # pandas的表個型態
df = df.drop("commid", axis = 1)
df = df.drop("sq", axis = 1)
df = df.drop("a", axis = 1)
df = df.drop("type", axis = 1)
df = df.drop("bn", axis = 1)
df = df.drop("city", axis = 1)

# df["ans"] = data_shilin["target"]
df

# df["f"]

# " 待思考調整形式 "
# floor = df["f"].unique()
# floor
# floor2idx = {floor[i]:i for i in range(len(floor))}
# floor2idx = {i:floor[i] for i in range(len(floor))}
# floor2idx

,AA11,AA12,b,bs,cp,e,el,es,f,fi,...,punit,r,reid,s,t,tp,tunit,twn,unit,v
0,住,,公寓(5樓含以下無電梯),87.39%,,111/10/03,無,,三層/四層,,...,1,28,,22.68,房地(土地+建物),"7,500,000",1,A15,2,3房1廳2衛
1,住,,華廈(10層含以下有電梯),65.01%,,111/09/08,有,,六層/六層,,...,1,51,,29.52,房地(土地+建物),"27,350,000",1,A15,2,3房2廳2衛
2,住,,公寓(5樓含以下無電梯),82.82%,,111/09/15,無,,二層/四層,,...,1,28,,21.15,房地(土地+建物),"6,645,000",1,A15,2,2房2廳2衛
3,工,,住宅大樓(11層含以上有電梯),50.14%,280,111/09/05,有,71.93%,八層/十四層,,...,1,73,,43.39,房地(土地+建物)+車位,"21,500,000",1,A15,2,
4,住,,公寓(5樓含以下無電梯),100.00%,,111/09/17,無,,二層/四層,,...,1,31,,28.57,房地(土地+建物),"17,500,000",1,A15,2,3房2廳2衛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,,華廈(10層含以下有電梯),44.01%,,110/10/08,有,,七層/九層,-1,...,1,25,,45.90,房地(土地+建物)+車位,"28,800,000",1,A15,2,3房2廳2衛
1472,住,,公寓(5樓含以下無電梯),81.31%,,110/10/30,無,,三層/五層,-1,...,1,24,,24.74,房地(土地+建物),"10,000,000",1,A15,2,3房2廳1衛
1473,商,,華廈(10層含以下有電梯),88.88%,,110/10/27,有,,三層/七層,-1,...,1,46,,28.81,房地(土地+建物),"15,200,000",1,A15,2,3房1廳2衛
1474,住,,公寓(5樓含以下無電梯),90.75%,,110/10/29,無,,二層/四層,-1,...,1,12,,30.66,房地(土地+建物),"17,800,000",1,A15,2,3房2廳2衛
1475,住,,住宅大樓(11層含以上有電梯),47.46%,150,110/10/12,有,55.87%,四層/十五層,0,...,1,35,,45.77,房地(土地+建物)+車位,"32,000,000",1,A15,2,2房2廳1衛

In [ ]:
import requests
import csv
import codecs
import pandas as pd
from sklearn.datasets import load_boston

url = requests.get("https://lvr.land.moi.gov.tw/SERVICE/QueryPrice/682df06cf19eff9d854d500b283b5dd9", params = 
                  {"q":"VTJGc2RHVmtYMThrUlJIdTRzYTRaTGI0UUZMVDNIQ3FQbUVIbUVxWG4wQVhERU43K2R5UCtJMWtMYVBmVHRNWU0yd1ZEYlBiaDhLSFQ2WHQ0RWgzeC9GU1F3OXBTQ1JkNXJtbnh6NCtpK0cwa2NiUGlpemlrKzQ0dFBiY2dJMkVJY2FJSHJzUWx4MEJrZ0l0bDE5RDVjOURJUlQ3STVIL0JIZzE1MlJJYVk1dVdGYjFnK1IvcEhjWU1vM2J6Wi9IY1p0U2N4RnJqTlNDcy9kOVBBZlo4b1RnQkRGQ3VtL3cyM3lkei8vVlptV21lbVNYcDNqbzFBTld4YlpnVnFuOHRTZVpGcG9Qdkd6a1V0VnpxVXNEOWR3M1N0bWxxWGduemhWTjJKM1JnZXZUSE9kWVhHLzVOVUFkd01JOTgyazdPVXV2WXY2SW5JK09VL1dPdk14dW5RVUpQZEthMEhOTG5BWWVRTnRtQ1IzaDFFQ3EzUno1U0ZuZllyMEJFNWxHaTZmZllna08rQ2drRFpnNE54cnV0ZDJVWDRnNDBFRXpNOU1xWmY1TlpOckppYVI3NVE1ckVTQ0FOV2l0MzZvTGdZU09qQmwwT3BYdjJJTWw3bnRMbzZNdlYxR2tDSHE5eU9kazU2NVZZVHVseWpJN01PemhKeFJ3L0FiSlc2Vzk3RkluS0Ftc2IzcGlyLzlaU1VKYXQzVDgvd05Icmo2bFhMUWN6TTRDSEJ4N2kzQXJtd1hFcC9FdksxU2Y1OHZqVTFyYlJmS3Jac0RrTm02YmIvbUYvNk5WNjRlMUVPdHhmWGZwZ3BVeDkydWF0N1c1T3NlbDlkUll5SU82U2t6ZXZLTUp2ajF3aHIvcm1QMG1rOGk4TmlWNkpkaFZUeXRwa3o2TVQ2dFQzTWwrMHpJWE1reUgrOGppeng4WDdzSXE="})
data_shilin = url.json()

# with codecs.open("shilin.csv", "r", encoding = "utf-8") as f:
#   data_shilin = list(csv.reader(f))

data_shilin


df = pd.DataFrame(data_shilin, columns = data_shilin[1]) # pandas的表個型態
df = df.drop("commid", axis = 1)
df = df.drop("sq", axis = 1)
df = df.drop("a", axis = 1)
df = df.drop("type", axis = 1)
df = df.drop("bn", axis = 1)
df = df.drop("city", axis = 1)

# df["ans"] = data_shilin["target"]
df

" 文字量化 "
# 住, 商, 其他, 6
using = df["AA11"].unique()
AA112idx = {using[i]:i for i in range(len(using))}
AA112idx = {i:using[i] for i in range(len(using))}
AA112idx

# 公寓, 華夏, 大樓, 透天
building = df["b"].unique()
building
building2idx = {building[i]:i for i in range(len(building))}
building2idx = {i:building[i] for i in range(len(building))}
building2idx

# 無, 有
elevator = df["el"].unique()
elevator
elevator2idx = {elevator[i]:i for i in range(len(elevator))}
elevator2idx = {i:elevator[i] for i in range(len(elevator))}
elevator2idx

import numpy as np
from sklearn.model_selection import train_test_split

# x = df.drop("ans", axis = 1) # 去除直欄 "ans", 產生一個新表格 x, 原 df 仍有 ans 直欄
x = np.array(df)
y = np.array(df["p"])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1) # 90% x, 10% x, 90% y, 10% y
show = x_test
print(show)
print("-----------------------")
x_train

# from sklearn.tree import DecisionTreeRegressor # 與 Classifier 不同

# reg = DecisionTreeRegressor(max_depth = 5) 
# reg.fit(x_train, y_train)

# import matplotlib.pyplot as plt
# from sklearn.tree import plot_tree
# plt.figure(figsize = (20, 20)) # 圖片放大, 數值越大, 呈現越大
# plot_tree(reg, 
#           filled = True,
#           max_depth = 2)

# from sklearn.metrics import r2_score
# pre = reg.predict(x_test)
# r2_score(y_test, pre)