<a href="https://colab.research.google.com/github/Liang130520/Tibame-TeamProject/blob/main/TeamProject_api_4%E7%89%88_%E8%B3%87%E6%96%99%E6%95%B4%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1009]:
# 無意義資料:a(地址), AA12(無資料), bn(社區名), commid(社區ID), id(排序ID),  pimg(照片), sq(一串不明意義文字)
# 缺失值太多, "cp", "es", "mark", "note", "punit", "reid"
# 要預測資料：p -> 每坪單價, tp -> 總價
# 需切割資料:f(樓層/總樓層), v(?房?廳?衛)

In [1010]:
import requests
import csv
import codecs
import pandas as pd
import json

# url = requests.get("https://lvr.land.moi.gov.tw/SERVICE/QueryPrice/682df06cf19eff9d854d500b283b5dd9", params = 
#                   {"q":"VTJGc2RHVmtYMThrUlJIdTRzYTRaTGI0UUZMVDNIQ3FQbUVIbUVxWG4wQVhERU43K2R5UCtJMWtMYVBmVHRNWU0yd1ZEYlBiaDhLSFQ2WHQ0RWgzeC9GU1F3OXBTQ1JkNXJtbnh6NCtpK0cwa2NiUGlpemlrKzQ0dFBiY2dJMkVJY2FJSHJzUWx4MEJrZ0l0bDE5RDVjOURJUlQ3STVIL0JIZzE1MlJJYVk1dVdGYjFnK1IvcEhjWU1vM2J6Wi9IY1p0U2N4RnJqTlNDcy9kOVBBZlo4b1RnQkRGQ3VtL3cyM3lkei8vVlptV21lbVNYcDNqbzFBTld4YlpnVnFuOHRTZVpGcG9Qdkd6a1V0VnpxVXNEOWR3M1N0bWxxWGduemhWTjJKM1JnZXZUSE9kWVhHLzVOVUFkd01JOTgyazdPVXV2WXY2SW5JK09VL1dPdk14dW5RVUpQZEthMEhOTG5BWWVRTnRtQ1IzaDFFQ3EzUno1U0ZuZllyMEJFNWxHaTZmZllna08rQ2drRFpnNE54cnV0ZDJVWDRnNDBFRXpNOU1xWmY1TlpOckppYVI3NVE1ckVTQ0FOV2l0MzZvTGdZU09qQmwwT3BYdjJJTWw3bnRMbzZNdlYxR2tDSHE5eU9kazU2NVZZVHVseWpJN01PemhKeFJ3L0FiSlc2Vzk3RkluS0Ftc2IzcGlyLzlaU1VKYXQzVDgvd05Icmo2bFhMUWN6TTRDSEJ4N2kzQXJtd1hFcC9FdksxU2Y1OHZqVTFyYlJmS3Jac0RrTm02YmIvbUYvNk5WNjRlMUVPdHhmWGZwZ3BVeDkydWF0N1c1T3NlbDlkUll5SU82U2t6ZXZLTUp2ajF3aHIvcm1QMG1rOGk4TmlWNkpkaFZUeXRwa3o2TVQ2dFQzTWwrMHpJWE1reUgrOGppeng4WDdzSXE="})
# data_shilin = url.json()

with open("shilin_house.json") as f:
  data_shilin = json.load(f)

# data_shilin

" 資料保存 "
# # json 檔
# with codecs.open("shilin_110_house.json", "w", encoding = "utf8") as f:
#   f.write(json.dumps(data_shilin, indent=2, ensure_ascii=False))

' 資料保存 '

In [1011]:
df = pd.DataFrame(data_shilin, columns = data_shilin[0])
df

,AA11,AA12,a,b,bn,bs,city,commid,cp,e,el,es,f,fi,g,id,j,k,l,lat,lon,m,mark,msg,note,p,pimg,pu,punit,r,reid,s,sq,t,tp,tunit,twn,type,unit,v
0,住,,延平北路六段１１６巷００２弄０００８號三樓#延平北路六段１１６巷２弄８號三樓,公寓(5樓含以下無電梯),,87.39%,A,,,111/10/03,無,,三層/四層,,41,0,1,1,0,25.089290,121.508230,無,,總價/總面積,,"330,711",bt_01.png,住家用,1,28,,22.68,3RZu85GSPSq1oKTPgw2ZM3+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"7,500,000",1,A15,Biz,2,3房1廳2衛
1,住,,中山北路五段７５６巷００３０號六樓#中山北路五段７５６巷３０號六樓,華廈(10層含以下有電梯),福林家園,65.01%,A,Z3TNcdK16AUe7vKRw44qB3+bDulj55Cqm9VU5qNLz60=,,111/09/08,有,,六層/六層,,21,1,1,1,0,25.099083,121.529616,有,,總價/總面積,陽台外推;其他增建;,"926,460",bt_06.png,住家用,1,51,,29.52,Z3TNcdK16AUe7vKRw44qB3+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"27,350,000",1,A15,Biz,2,3房2廳2衛
2,住,,永平街０３６巷０００４號二樓#永平街３６巷４號二樓,公寓(5樓含以下無電梯),,82.82%,A,,,111/09/15,無,,二層/四層,,42,2,1,1,0,25.090464,121.505469,無,,總價/總面積,親友、員工、共有人或其他特殊關係間之交易;,"314,218",bt_01.png,住家用,1,28,,21.15,YtjVG2aqsO1nOTP8cfpt83+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"6,645,000",1,A15,Biz,2,2房2廳2衛
3,工,,大南路０３２５號八樓之１#大南路３２５號八樓之１,住宅大樓(11層含以上有電梯),,50.14%,A,,280,111/09/05,有,71.93%,八層/十四層,,15,3,1,1,1,25.088385,121.516940,有,,(總價-車位總價)/(總面積-車位總面積),其他增建;,"618,304",bt_05.png,商業用,1,73,,43.39,hSDiLZmRLEsDler+X0p+5X+bDulj55Cqm9VU5qNLz60=,房地(土地+建物)+車位,"21,500,000",1,A15,Biz,2,
4,住,,中山北路六段１９５巷０１８弄０００４之１號二樓#中山北路六段１９５巷１８弄４之１號二樓,公寓(5樓含以下無電梯),,100.00%,A,,,111/09/17,無,,二層/四層,,48,4,1,1,0,25.108141,121.523815,無,,總價/總面積,現況格局另有一室(無法擺床),"612,635",bt_01.png,住家用,1,31,,28.57,uqKptUVohZBJsldbw2fn+n+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"17,500,000",1,A15,Biz,2,3房2廳2衛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,,福華路０００２之１號七樓#福華路２之１號七樓,華廈(10層含以下有電梯),隨河,44.01%,A,2A4IvGn+WwubXtU0nWTle3+bDulj55Cqm9VU5qNLz60=,,110/10/08,有,,七層/九層,-1,3,1471,1,1,1,25.100296,121.523722,有,,總價/總面積,,"627,474",bt_06.png,住家用,1,25,,45.90,2A4IvGn+WwubXtU0nWTle3+bDulj55Cqm9VU5qNLz60=,房地(土地+建物)+車位,"28,800,000",1,A15,Biz,2,3房2廳2衛
1472,住,,社子街０１２３號三樓#社子街１２３號三樓,公寓(5樓含以下無電梯),,81.31%,A,,,110/10/30,無,,三層/五層,-1,43,1472,1,1,0,25.088497,121.505272,無,,總價/總面積,,"404,129",bt_01.png,住家用,1,24,,24.74,vIP5rfleSp3YauVl1Ss0u3+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"10,000,000",1,A15,Biz,2,3房2廳1衛
1473,商,,天母西路００６９號三樓#天母西路６９號三樓,華廈(10層含以下有電梯),齊賢,88.88%,A,OcR10WdFUOLi+IVN+/7jtX+bDulj55Cqm9VU5qNLz60=,,110/10/27,有,,三層/七層,-1,35,1473,2,1,0,25.118698,121.525476,有,,總價/總面積,親友、員工、共有人或其他特殊關係間之交易;陽台外推;(包含)公共設施保留地(用地);,"527,537",bt_06.png,住家用,1,46,,28.81,OcR10WdFUOLi+IVN+/7jtX+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"15,200,000",1,A15,Biz,2,3房1廳2衛
1474,住,,雨聲街００６巷０００２號二樓#雨聲街６巷２號二樓,公寓(5樓含以下無電梯),,90.75%,A,,,110/10/29,無,,二層/四層,-1,44,1474,1,1,0,25.101006,121.529684,無,,總價/總面積,陽台外推;其他增建;,"580,536",bt_01.png,住家用,1,12,,30.66,/qt77uy76YN/X/TC60Djm3+bDulj55Cqm9VU5qNLz60=,房地(土地+建物),"17,800,000",1,A15,Biz,2,3房2廳2衛
1475,住,,承德路四段００８８號四樓#承德路四段８８號四樓,住宅大樓(11層含以上有電梯),,47.46%,A,,150,110/10/12,有,55.87%,四層/十五層,0,,1475,1,1,1,25.082847,121.523063,有,,(總價-車位總價)/(總面積-車位總面積),預售屋、或土地及建物分件登記案件;,"784,519",bt_05.png,住家用,1,35,,45.77,vLA61CRYDzP2s9rnubqbPH+bDulj55Cqm9VU5qNLz60=,房地(土地+建物)+車位,"32,000,000",1,A15,Biz,2,2房2廳1衛

In [1012]:
df = pd.DataFrame(data_shilin, columns = data_shilin[0]) # pandas的表個型態
df = df.drop(["a", "AA12", "bn", "commid", "id", "pimg", "sq", "cp", "es", "mark", "note", "punit", "reid"], axis = 1)

# df["ans"] = data_shilin["p"] # 看要預測單價或總價
# df["ans"] = data_shilin["tp"] # 看要預測單價或總價

pd.set_option('display.max_columns', 500)
df

# 無意義資料:a(地址), AA12(無資料), bn(社區名), commid(社區ID), id(排序ID), lat(經度), lon(緯度),  pimg(照片), sq(一串不明意義文字) delete complete
# 缺失值太多, "cp", "es", "mark", "note", "punit", "reid" delete complete

,AA11,b,bs,city,e,el,f,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,v
0,住,公寓(5樓含以下無電梯),87.39%,A,111/10/03,無,三層/四層,,41,1,1,0,25.089290,121.508230,無,總價/總面積,"330,711",住家用,28,22.68,房地(土地+建物),"7,500,000",1,A15,Biz,2,3房1廳2衛
1,住,華廈(10層含以下有電梯),65.01%,A,111/09/08,有,六層/六層,,21,1,1,0,25.099083,121.529616,有,總價/總面積,"926,460",住家用,51,29.52,房地(土地+建物),"27,350,000",1,A15,Biz,2,3房2廳2衛
2,住,公寓(5樓含以下無電梯),82.82%,A,111/09/15,無,二層/四層,,42,1,1,0,25.090464,121.505469,無,總價/總面積,"314,218",住家用,28,21.15,房地(土地+建物),"6,645,000",1,A15,Biz,2,2房2廳2衛
3,工,住宅大樓(11層含以上有電梯),50.14%,A,111/09/05,有,八層/十四層,,15,1,1,1,25.088385,121.516940,有,(總價-車位總價)/(總面積-車位總面積),"618,304",商業用,73,43.39,房地(土地+建物)+車位,"21,500,000",1,A15,Biz,2,
4,住,公寓(5樓含以下無電梯),100.00%,A,111/09/17,無,二層/四層,,48,1,1,0,25.108141,121.523815,無,總價/總面積,"612,635",住家用,31,28.57,房地(土地+建物),"17,500,000",1,A15,Biz,2,3房2廳2衛
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,華廈(10層含以下有電梯),44.01%,A,110/10/08,有,七層/九層,-1,3,1,1,1,25.100296,121.523722,有,總價/總面積,"627,474",住家用,25,45.90,房地(土地+建物)+車位,"28,800,000",1,A15,Biz,2,3房2廳2衛
1472,住,公寓(5樓含以下無電梯),81.31%,A,110/10/30,無,三層/五層,-1,43,1,1,0,25.088497,121.505272,無,總價/總面積,"404,129",住家用,24,24.74,房地(土地+建物),"10,000,000",1,A15,Biz,2,3房2廳1衛
1473,商,華廈(10層含以下有電梯),88.88%,A,110/10/27,有,三層/七層,-1,35,2,1,0,25.118698,121.525476,有,總價/總面積,"527,537",住家用,46,28.81,房地(土地+建物),"15,200,000",1,A15,Biz,2,3房1廳2衛
1474,住,公寓(5樓含以下無電梯),90.75%,A,110/10/29,無,二層/四層,-1,44,1,1,0,25.101006,121.529684,無,總價/總面積,"580,536",住家用,12,30.66,房地(土地+建物),"17,800,000",1,A15,Biz,2,3房2廳2衛
1475,住,住宅大樓(11層含以上有電梯),47.46%,A,110/10/12,有,四層/十五層,0,,1,1,1,25.082847,121.523063,有,(總價-車位總價)/(總面積-車位總面積),"784,519",住家用,35,45.77,房地(土地+建物)+車位,"32,000,000",1,A15,Biz,2,2房2廳1衛

In [1013]:
" 分割 f "
" 取得購買的第一樓層 "
def change(n1):
  if pd.isna(n1):
    return n1
  else:
    x = n1.split("/")[0].strip()
    if x.find(",") != -1:
      return x.split(",")[0].strip()
    else:
      return x

df["flr"] = df["f"].apply(change)

" 額外的第二樓層 "
df["flr"] = df["f"].apply(change)
df_flr = df["flr"].unique()

def change(n2):
  if pd.isna(n2):
    return n2
  else:
    x = n2.split("/")[0].strip()
    if (x.find(",") != -1):
      return x.split(",")[1]
    else:
      return None

df["extraflr"] = df["f"].apply(change)

" 額外的第三樓層 "
def change(n3):
  if pd.isna(n3):
    return n3
  else:
    x = n3.split("/")[0].strip()
    if (x.find(",") != -1):
      if len(x.split(",")) >= 3:
        return x.split(",")[2]
      else:
        return None
    else:
      return None
df["2extraflr"] = df["f"].apply(change)

" 額外的第四樓層 "
def change(n4):
  if pd.isna(n4):
    return n4
  else:
    x = n4.split("/")[0].strip()
    if (x.find(",") != -1):
      if len(x.split(",")) >= 3:
        if len(x.split(",")) >= 4:
          return x.split(",")[3]
        else:
          return None
      else:
        return None
    else:
      return None

df["3extraflr"] = df["f"].apply(change)

" 總樓層 "
def change(s):
  if pd.isna(s):
    return s
  else:
    return s.split("/")[1].strip()
df["totalflr"] = df["f"].apply(change)
df_totalflr = df["totalflr"].unique()
df_totalflr

array(['四層', '六層', '十四層', '十一層', '十八層', '十三層', '三層', '五層', '二層', '七層',
       '十二層', '八層', '二十一層', '九層', '--', '一層', '十層', '十六層', '十五層', '二十四層',
       '二十二層', '三十八層', '十九層', '十七層'], dtype=object)

In [1014]:
" 確認樓層分割狀況 "
# totalflr_unique.sort_values(ascending = True)
# df_totalflr = df["totalflr"].value_counts()
# df_totalflr

# 需切割資料:f(樓層/總樓層) delete complete

' 確認樓層分割狀況 '

In [1015]:
" v 切割(?房?廳?衛) " # 先切?房
def change(r1):
  if pd.isna(r1):
    return r1
  else:
    return r1.split("房")[0]
df["room"] = df["v"].apply(change)

# 再切廳
def change(r2):
  if pd.isna(r2):
    return r2
  else:
    return r2.split("廳")[0].split("房")[-1]
df["office"] = df["v"].apply(change)

# 再切衛
def change(r3):
  if pd.isna(r3):
    return r3
  else:
    return r3.split("廳")[-1].split("衛")[0]
df["toilet"] = df["v"].apply(change)

# 需切割資料:v(?房?廳?衛) depart complete

In [1016]:
" 確認是否有 "" 存在 "
# df_pu = df["pu"].unique()
# df_pu = df["pu"].value_counts()
# df_pu

' 確認是否有  存在 '

In [1017]:
" bs 有 %, 無法做 median, 先分割 "
def change(m):
  if pd.isna(m):
    return m
  else:
    return m.split("%")[0]
df["bs"] = df["bs"].apply(change)

In [1018]:
" 樓層名轉換數值"
# 類別值:AA11, b, city, el, m, msg, pu, t, twn, type
# 未知定義, 先當類別:el, m

column_dict = {"":None,None:0, '陽台':1, '平台':1, '屋頂突出物':1, '夾層':1, '電梯樓梯間':1, '騎樓':1, '陽臺':1, '地下一層':0, '地下層':0, '全':100, '一層':1, '二層':2, '三層':3, '四層':4, '五層':5, '六層':6, '七層':7, '八層':8, '九層':9, '十層':10, '十一層':11, '十二層':12, '十三層':13, '十四層':14, '十五層':15, '十六層':16, '十七層':17, '十八層':18, '十九層':19, '二十層':20, '二十一層':21, '二十二層':22, '二十三層':23, '二十四層':24, '二十五層':25, '二十六層':26, '二十七層':27, '二十八層':28, '二十九層':29, '三十層':30, '三十一層':31, '三十二層':32, '三十三層':33, '三十四層':34, '三十五層':35, '三十六層':36, '三十七層':37, '三十八層':38, '三十九層':39, '四十層':40, '四十一層':41, '四十二層':42, '四十三層':43, '四十四層':44, '四十五層':45, '四十六層':46, '四十七層':47, '四十八層':48, '四十九層':49, '五十層':50}

df = df.replace({"flr": column_dict})
df = df.replace({"extraflr": column_dict})
df = df.replace({"2extraflr": column_dict})
df = df.replace({"3extraflr": column_dict})
df = df.replace({"totalflr": column_dict})
df = df.replace({"pu": column_dict})

" 將 "" 轉換空值 "
# 數值:bs, e, g, j, k, l, lat, lon, s, flr, extraflr, 2extraflr, 3extraflr, totlaflr, room, offic, toilet
# 未知定義, 先當數值:fi, r, tunit, unit

column_sort_dict = {"":None}

df = df.replace({"bs": column_sort_dict})
df = df.replace({"fi": column_sort_dict})
df = df.replace({"room": column_sort_dict})
df = df.replace({"office": column_sort_dict})
df = df.replace({"toilet": column_sort_dict})

df = df.drop(["f", "v"], axis = 1) # 難分辨資料已分割, 去除該資料
df

,AA11,b,bs,city,e,el,fi,g,j,k,l,lat,lon,m,msg,p,pu,r,s,t,tp,tunit,twn,type,unit,flr,extraflr,2extraflr,3extraflr,totalflr,room,office,toilet
0,住,公寓(5樓含以下無電梯),87.39,A,111/10/03,無,None,41,1,1,0,25.089290,121.508230,無,總價/總面積,"330,711",住家用,28,22.68,房地(土地+建物),"7,500,000",1,A15,Biz,2,3,0,0,0,4,3,1,2
1,住,華廈(10層含以下有電梯),65.01,A,111/09/08,有,None,21,1,1,0,25.099083,121.529616,有,總價/總面積,"926,460",住家用,51,29.52,房地(土地+建物),"27,350,000",1,A15,Biz,2,6,0,0,0,6,3,2,2
2,住,公寓(5樓含以下無電梯),82.82,A,111/09/15,無,None,42,1,1,0,25.090464,121.505469,無,總價/總面積,"314,218",住家用,28,21.15,房地(土地+建物),"6,645,000",1,A15,Biz,2,2,0,0,0,4,2,2,2
3,工,住宅大樓(11層含以上有電梯),50.14,A,111/09/05,有,None,15,1,1,1,25.088385,121.516940,有,(總價-車位總價)/(總面積-車位總面積),"618,304",商業用,73,43.39,房地(土地+建物)+車位,"21,500,000",1,A15,Biz,2,8,0,0,0,14,None,None,None
4,住,公寓(5樓含以下無電梯),100.00,A,111/09/17,無,None,48,1,1,0,25.108141,121.523815,無,總價/總面積,"612,635",住家用,31,28.57,房地(土地+建物),"17,500,000",1,A15,Biz,2,2,0,0,0,4,3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,住,華廈(10層含以下有電梯),44.01,A,110/10/08,有,-1,3,1,1,1,25.100296,121.523722,有,總價/總面積,"627,474",住家用,25,45.90,房地(土地+建物)+車位,"28,800,000",1,A15,Biz,2,7,0,0,0,9,3,2,2
1472,住,公寓(5樓含以下無電梯),81.31,A,110/10/30,無,-1,43,1,1,0,25.088497,121.505272,無,總價/總面積,"404,129",住家用,24,24.74,房地(土地+建物),"10,000,000",1,A15,Biz,2,3,0,0,0,5,3,2,1
1473,商,華廈(10層含以下有電梯),88.88,A,110/10/27,有,-1,35,2,1,0,25.118698,121.525476,有,總價/總面積,"527,537",住家用,46,28.81,房地(土地+建物),"15,200,000",1,A15,Biz,2,3,0,0,0,7,3,1,2
1474,住,公寓(5樓含以下無電梯),90.75,A,110/10/29,無,-1,44,1,1,0,25.101006,121.529684,無,總價/總面積,"580,536",住家用,12,30.66,房地(土地+建物),"17,800,000",1,A15,Biz,2,2,0,0,0,4,3,2,2
1475,住,住宅大樓(11層含以上有電梯),47.46,A,110/10/12,有,0,,1,1,1,25.082847,121.523063,有,(總價-車位總價)/(總面積-車位總面積),"784,519",住家用,35,45.77,房地(土地+建物)+車位,"32,000,000",1,A15,Biz,2,4,0,0,0,15,2,2,1

In [1019]:
df
df.isna() # 確認哪些是空值
s = df.isna().sum() # 確認每欄有幾個空值
s[s > 0]

bs        73
fi        72
pu         3
room      95
office    95
toilet    95
dtype: int64

In [1020]:
" 補類別值 "
# 自認非空值, 待補類別值 pu

# df["pu"].value_counts() # 取得 pu 欄位內值的數量
# df["pu"].value_counts().max() # 取得 pu 類別內數量最多的數量
mostidx = df["pu"].value_counts().idxmax() # 取得 pu 內最多數量的值

df["pu"] = df["pu"].fillna(mostidx) # fillna 空值欄填入資料, mostidx 為[(最多的類別)的值]

In [1021]:
" 補數值 "
# 自認非空值, 待補數值 bs, fi, room, office, toilet

df.median() 

bs_med = df["bs"].median()
df["bs"] = df["bs"].fillna(bs_med)

fi_med = df["fi"].median()
df["fi"] = df["fi"].fillna(fi_med)

room_med = df["room"].median()
df["room"] = df["room"].fillna(room_med)

office_med = df["office"].median()
df["office"] = df["office"].fillna(office_med)

toilet_med = df["toilet"].median()
df["toilet"] = df["toilet"].fillna(toilet_med)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.

In [1022]:
df
df.isna() # 確認哪些是空值
s = df.isna().sum() # 確認每欄有幾個空值
# s
s[s > 0]

Series([], dtype: int64)

In [1023]:
" 資料保存 "

# CSV 檔
df.to_csv( "shilin_house.csv"  , index=False )